on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}:latest -t ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}

