on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 何故かbuildxだと -t でタグがつかない。ローカルだとつくのに。
      #- name: Build and push
      #  run: |
      #    docker buildx build -t ${{ env.REGISTRY }}/${{ github.repository }}:latest -t ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }} --platform linux/arm64 .
      #    docker image ls 
      #    docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest
      #    docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest,${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}

